### ISSUE TITLE
Investigate Required Changelog File/Entry Workflow

### ISSUE THREAD

**Issue by bflad** [hashicorp/go-changelog#8]
## Description

Certain projects may want an easy GitHub Actions workflow to require changelog entries for pull requests that are managed by `go-changelog`. Currently, this can be done, but requires some glue scripting, such as what is done by Consul.

It would be great if projects could quickly configure a workflow to enable this behavior. This could be potentially done along with other changelog checks as shown below:

```yaml
 - uses: hashicorp/go-changelog-check
    with:
      pull-request-number: {{ github.XX }}
      required: true
      required-ignore-labels: ["pr/no-changelog"]
```

## References

- https://github.com/hashicorp/go-changelog/issues/6
- https://github.com/hashicorp/consul/blob/a37c1e84667c48658fad4da0559c00300872b8f2/.github/workflows/changelog-checker.yml
